name: Plugin Tests

on:
  pull_request:
    branches: [main, release-* ]
    paths:
      - "cmd/cli/plugin/cluster/**"
      - "cmd/cli/plugin/managementcluster/**"
      - 'tkg/**'
      - 'pkg/v1/providers/**'
      - '.github/workflows/plugin_tests.yaml'

concurrency:
  group: ${{ format('plugin-tests-{0}', github.head_ref) }}
  cancel-in-progress: true

jobs:
  build:
    name: Plugin Tests
    runs-on: tkg
    steps:
      - uses: ./github/actions/workflow-setup
        with:
          full-clean: "true"
          use-node: "false"

      - name: Cleanup
        run: rm -rf ~/.tanzu ~/.tkg ~/.config ~/.cache/tanzu; docker kill $(docker ps -q) | true; docker system prune -a --volumes -f

      - name: Install Tanzu CLI
        run: |
          make install-cli
          tanzu config set features.global.context-aware-cli-for-plugins true

      - name: Install CLI plugins
        run: |
          tanzu plugin install all --local artifacts/linux/amd64/cli/
          tanzu plugin install all --local artifacts-admin/linux/amd64/cli/

      - name: Run cluster test plugin
        run: tanzu test plugin cluster
