name: Release Staging

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Release Staging
    runs-on: ubuntu-latest
    steps:
    - uses: ./github/actions/workflow-setup

    - name: Build
      run: BUILD_VERSION=dev make all

    - name: Verify
      run: |
        make verify

    - name: Test
      run: make test

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage1.txt,./coverage2.txt,./coverage3.txt,./addons/coverage.txt,./pinniped-components/post-deploy/coverage.txt,./pinniped-components/tanzu-auth-controller-manager/coverage.txt,./cli/core/coverage.txt,./cli/runtime/coverage.txt,./tkg/coverage.txt,./featuregates/client/cover.out,./featuregates/controller/cover.out,./capabilities/client/cover.out,./capabilities/controller/cover.out,./cmd/cli/plugin-admin/builder/cover.out,./cmd/cli/plugin-admin/codegen/cover.out,./cmd/cli/plugin-admin/test/cover.out,./apis/config/cover.out,./apis/run/cover.out,./packageclients/cover.out,./apis/addonconfigs/cover.out,./apis/cli/cover.out,./apis/core/cover.out,./cmd/cli/plugin/feature/cover.out,./cmd/cli/plugin/login/cover.out,./cmd/cli/plugin/package/cover.out,./cmd/cli/plugin/pinniped-auth/cover.out,./cmd/cli/plugin/secret/cover.out

    - id: upload-cli-artifacts
      # do not upload unsigned/untested artifacts to GCP bucket
      if: ${{ false }}
      uses: google-github-actions/upload-cloud-storage@v0.10.2
      with:
        path: ./artifacts
        destination: tanzu-cli-framework
        credentials: ${{ secrets.GCP_BUCKET_SA }}

    - id: upload-cli-admin-artifacts
      # do not upload unsigned/untested artifacts to GCP bucket
      if: ${{ false }}
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./artifacts-admin
        destination: tanzu-cli-admin-plugins
        credentials: ${{ secrets.GCP_BUCKET_SA }}
